### ISSUE TITLE
Blender 2.8+ Crashes

### ISSUE THREAD

**Issue by NayamAmarshe** [kugelrund/io_scene_pop#1]
This addon is perfect but the only thing missing is the 2.8+ support. It's be amazing if it gets 2.8+ support, can't wait to render all the levels with modern textures.

**Comment by kugelrund** [comment]
With https://github.com/kugelrund/io_scene_pop/commit/e004a5362fa05c0970307fec8037104fe6e3ee51 the plugin is now updated for use with Blender 2.8 and above. Took some things from https://github.com/ihavenick/io_scene_pop/commit/6aea9d318d3febe4e94faa03b2e90af967d2bd91, thanks for that.

**Comment by NayamAmarshe** [comment]
> With [e004a53](https://github.com/kugelrund/io_scene_pop/commit/e004a5362fa05c0970307fec8037104fe6e3ee51) the plugin is now updated for use with Blender 2.8 and above. Took some things from [ihavenick@6aea9d3](https://github.com/ihavenick/io_scene_pop/commit/6aea9d318d3febe4e94faa03b2e90af967d2bd91), thanks for that.

Thank you! Me and @ihavenick tried editing the code haha, could get it working but there were some bugs. Thank you for your time, I'll try the update ASAP :D
